---

- hosts: localhost
  connection: local

  tasks:
    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - zsh
        # - oh-my-zsh
        - z
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - google-drive
        - postico
        - sequel-pro

    - git: repo=https://github.com/jacebrowning/dotfiles
           dest=~/.dotfiles
           version=HEAD

  roles:
    - profile-all
    - profile-developer

  vars:
    # - computername: "Jace's MacBook Pro"
    - git_user_name: jacebrowning
    - git_user_email: jacebrowning@gmail.com
    
