---

- hosts: localhost
  connection: local

  tasks:
    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - thefuck
        - zsh
        - z

    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - sequel-pro
        - postico
        - calibre
        - macpilot
        - transmission
        - lastfm

    - name: install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh
           dest=~/.oh-my-zsh

    - name: set custom shell
      command: chsh -s /bin/zsh Browning
      become: true

    - name: link to this configuration code
      file: src=/usr/local/superlumic/config
            dest=~/Documents/superlumic-config
            state=link

    - name: apply global dotfiles
      git: repo=https://github.com/jacebrowning/dotfiles
           dest=~/.dotfiles
           update=no
    - file: src=~/.dotfiles
            dest=~/Documents/dotfiles
            state=link
    - command: make -C ~/Documents/dotfiles

    - name: apply sublime text settings
      git: repo=https://github.com/jacebrowning/sublime-settings
           dest="~/Library/Application Support/Sublime Text 3/Packages/User"
           update=no
    - file: src="~/Library/Application Support/Sublime Text 3/Packages/User"
            dest=~/Documents/sublime-settings
            state=link

    - name: install personal python packages
      pip: executable=~/.pyenv/shims/pip
           name={{item.name}}
           version={{item.version}}
      with_items:
        - { name: mine, version: 1.4 }

  roles:
    - profile-all
    - profile-developer

  vars:
    - git_user_name: Jace Browning
    - git_user_email: jacebrowning@gmail.com
