---

- hosts: localhost
  connection: local

  tasks:
    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - zsh
        # - oh-my-zsh
        - z

    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - google-drive
        - postico
        - sequel-pro

    - name: set custom shell
      command: chsh -s /bin/zsh Browning
      become: true

    - name: apply global dotfiles
      git: repo=https://github.com/jacebrowning/dotfiles
           dest=~/.dotfiles
           update=no
    - file: src=~/.dotfiles
            dest=~/Programs/dotfiles
            state=link
    - command: make -C ~/Programs/dotfiles
    - name: apply sublime text settings
      git: repo=https://github.com/jacebrowning/sublime-settings
           dest="~/Library/Application Support/Sublime Text 3/Packages/User"
           update=no
    - file: src="~/Library/Application Support/Sublime Text 3/Packages/User"
            dest=~/Programs/sublime-settings
            state=link

    - name: install personal python packages
      pip: executable=~/.pyenv/shims/pip
           name={{item.name}}
           version={{item.version}}
      with_items:
        - { name: thefuck, version: 3.11 }

  roles:
    - profile-all
    - profile-developer

  vars:
    # - computername: "Jace's MacBook Pro"
    - git_user_name: Jace Browning
    - git_user_email: jacebrowning@gmail.com
