---

- name: install brew applications for all users
  homebrew: name={{item}} state=latest
  with_items:
    - vim

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-chrome
    - libreoffice
    - vlc
    - slack
    - gitter
    - flowdock
    - sococo
    - screenhero
    - lastpass
    - sublime-text
