---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - rsync
    - postgres
    - mongodb
    - graphviz
    - pandoc

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - github-desktop
    - p4merge
    - firefox

- name: install pyenv
  homebrew: name=pyenv state=latest

# pyenv

- name: install python versions
  command: pyenv install --skip-existing {{item}}
  with_items:
    - 2.7.12
    - 3.5.0
    - 3.5.2
    - 3.6.0b1

- name: set global python versions
  copy:
    dest: ~/.pyenv/version
    content: |
      3.5.2
      2.7.12

- name: rehash pyenv shims
  command: pyenv rehash

- name: install python packages
  pip: executable=~/.pyenv/shims/pip
       name={{item.name}}
       version={{item.version}}
  with_items:
    - { name: mine, version: 1.0 }
    - { name: gitman, version: 1.0.2 }
