---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - rsync
    - pv
    - jq
    - shellcheck
    - openjpeg
    - imagemagick
    - freetype
    - portaudio
    - ffmpeg
    - direnv
    - mysql
    - postgres
    - mongodb
    - memcached
    - redis
    - rabbitmq
    - pass
    - heroku
    - phantomjs
    - graphviz
    - pandoc

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - github-desktop
    - diffmerge
    - p4merge
    - vagrant
    - firefox
    - ngrok

# pyenv

- name: install pyenv
  homebrew: name=pyenv state=latest

- name: install python versions
  command: >
    env PYTHON_CONFIGURE_OPTS="--enable-framework"
    pyenv install --skip-existing {{item}}
  with_items:
    - 2.7.13
    - 3.6.1

- name: set global python versions
  copy:
    dest: ~/.pyenv/version
    content: |
      3.6.1
      2.7.13

- name: rehash pyenv shims
  command: pyenv rehash

- name: install developer python packages
  pip: executable=~/.pyenv/shims/pip
       name={{item.name}}
       version={{item.version}}
  with_items:
    - { name: pip, version: 9.0.1 }
    - { name: virtualenv, version: 15.0.3 }

# rbenv

- name: install rbenv
  homebrew: name=rbenv state=latest

- name: install ruby versions
  command: rbenv install --skip-existing {{item}}
  with_items:
    - 2.2.5
    - 2.3.3
    - 2.4.0

- name: set global ruby versions
  copy:
    dest: ~/.rbenv/version
    content: |
      2.4.0

- name: rehash rbenv shims
  command: rbenv rehash

- name: install developer ruby packages
  gem: executable=~/.rbenv/shims/gem
       name={{item.name}}
       version={{item.version}}
  with_items:
    - { name: bundler, version: 1.15.0 }

# nodenv

- name: install nodenv
  homebrew: name=nodenv state=latest

- name: install node versions
  command: nodenv install --skip-existing {{item}}
  with_items:
    - 6.9.1

- name: set global node versions
  copy:
    dest: ~/.nodenv/version
    content: |
      6.9.1

- name: rehash nodenv shims
  command: nodenv rehash

- name: install developer node packages
  npm: executable=~/.nodenv/shims/npm
       global=yes
       name={{item.name}}
       version={{item.version}}
  with_items:
    - { name: diff-so-fancy, version: 0.11.2 }
